default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: scratchgolfnyc_development

test:
  <<: *default
  database: scratchgolfnyc_test

production:
  <<: *default
  database: scratchgolfnyc_production
  username: scratchgolfnyc
  password: <%= ENV['SCRATCHGOLFNYC_DATABASE_PASSWORD'] %>
